matrix:
 include:
  - language: c
    sudo: false # only for faster builds
    compiler: 
     - clang
     - gcc
    script:
      - gcc -o door door.c // we can use gcc instead of clang too
      - ./door
